apiVersion: apps/v1
kind: Deployment
metadata:
 name: http-bin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-bin
  template:
    metadata:
      labels:
        app: http-bin
    spec:
      containers:
        - name: http-bin
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: http-bin-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: http-bin
