apiVersion: v1
kind: Service
metadata:
  name: http-bin
spec:
  selector:
    app: http-bin
  type: NodePort
  ports:
    - port: 80
      name: http-bin
      targetPort: 8080
      nodePort: 32000


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: http-bin
spec:
  serviceName: http-bin
  replicas: 10
  selector:
    matchLabels:
      app: http-bin
  template:
    metadata:
      labels:
        app: http-bin
    spec:
      containers:
        - name: http-bin
          image: ccr.ccs.tencentyun.com/k8s-tutorial/test-k8s:v1
          imagePullPolicy: IfNotPresent

