apiVersion: v1
kind: Service
metadata:
  name: yangfan-master-service
spec:
  selector:
    app: yangfan-master
  ports:
    - protocol: TCP
      port: 7966
      targetPort: 7966
    - protocol: TCP
      port: 9093
      targetPort: 9093
    - protocol: TCP
      port: 9092
      targetPort: 9092