apiVersion: v1
kind: ConfigMap
metadata:
  name: yangfan-grafana-prometheus-config
data:
  yangfan.prometheus.prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://yangfan-prometheus:9090

