apiVersion: v1
kind: Service
metadata:
  name: yangfan-grafana
spec:
  selector:
    app: yangfan-grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31030