apiVersion: apps/v1
kind: Deployment
metadata:
  name: yangfan-server
  namespace: yangfan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yangfan-server
  template:
    metadata:
      labels:
        app: yangfan-server
    spec:
      containers:
        - name: yangfan-server
          image: yangfanz/serverserver{{ if or (eq .Values.IMAGE_DEBUG_SUFFIX "true") (eq .Values.IMAGE_DEBUG_SUFFIX "debug") }}debug{{end | default "" }}:{{ if .Values.IMAGE_TAG }}{{ .Values.IMAGE_TAG }}{{ else }}latest{{ end | default "latest" }}
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 7967
              protocol: TCP
          volumeMounts:
            - name: docker-config-yaml
              mountPath: /yangfan/docker.config.yaml
              subPath: docker.config.yaml
      volumes:
        - name: docker-config-yaml
          configMap:
            name: docker-config-yaml
