apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yangfan-work
  namespace: yangfan
spec:
  replicas: 3
  serviceName: yangfan-work
  selector:
    matchLabels:
      app: yangfan-work
  template:
    metadata:
      labels:
        app: yangfan-work
    spec:
      containers:
        - name: yangfan-work
          image: yangfanz/work:latest
          env:
            - name: MASTER_SERVER
              value: yangfan-master-service
          ports:
            - containerPort: 7966
              protocol: TCP
          volumeMounts:
            - name: docker-config-yaml
              mountPath: /yangfan/docker.config.yaml
              subPath: docker.config.yaml
      volumes:
        - name: docker-config-yaml
          configMap:
            name: docker-config-yaml