apiVersion: v1
kind: Service
metadata:
  name: yangfan-web
spec:
  selector:
    app: yangfan-web
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
      protocol: TCP
