apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcdemo-deployment
  labels:
    app: grpcdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcdemo
  template:
    metadata:
      labels:
        app: grpcdemo
    spec:
      containers:
        - name: grpcdemo
          image: registry.cn-hangzhou.aliyuncs.com/yangfanz/grpcdemo
          ports:
            - containerPort: 7967
