apiVersion: v1
kind: Service
metadata:
  name: grpcdemo
spec:
  selector:
    app: grpcdemo
  ports:
    - protocol: TCP
      port: 7967
      targetPort: 7967
      nodePort: 31967
  type: NodePort
