version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  server:
    build:
      context: ../../
      dockerfile: ./server/Dockerfile
    container_name: yangfan-server
    restart: always
    ports:
      - '8888:8888'
    networks:
      network:
        ipv4_address: 177.7.0.12

  web:
    build:
      context: ../../web
      dockerfile: ./Dockerfile
    container_name: yangfan-web
    restart: always
    ports:
      - '8080:8080'
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  master:
    build:
      context: ../../
      dockerfile: ./master/Dockerfile
    container_name: yangfan-master
    restart: always
    ports:
      - '7966:7966'
      - '9093:9093'
      - '9092:9092'
    networks:
      network:
        ipv4_address: 177.7.0.15

  work:
    build:
      context: ../../
      dockerfile: ./work/Dockerfile
    container_name: yangfan-work
    restart: always
    networks:
      network:
        ipv4_address: 177.7.0.16