version: "3"

services:
  yangfan-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: yangfan-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yangfan
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/yangfan.sql:/docker-entrypoint-initdb.d/yangfan.sql

  yangfan-mysql-init:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: yangfan-mysql
    restart: always
    ports:
      - '33016:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yangfan
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/yangfan.sql:/docker-entrypoint-initdb.d/yangfan.sql