version: "3"

networks:
  yangfan_network:
    ipam:
      driver: default
      config:
        - subnet: '177.8.0.0/16'

services:
  yangfan-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: yangfan-mysql
    restart: always
    networks:
      - yangfan_network
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yangfan
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/yangfan.sql:/docker-entrypoint-initdb.d/yangfan.sql

  yangfan-server:
    image: registry.cn-hangzhou.aliyuncs.com/yangfanz/server:latest
    container_name: yangfan-server
    networks:
      - yangfan_network
    depends_on:
      - yangfan-mysql
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml

  web:
    image: registry.cn-hangzhou.aliyuncs.com/yangfanz/web:latest
    container_name: web
    networks:
      - yangfan_network
    depends_on:
      - yangfan-server
    restart: always
    # 飞书登陆环境变量
    environment:
      - ENV_VITE_FS_APP_ID=cli_a241057640bd900c
      - ENV_VITE_FS_LOGIN=http://localhost:8080/api/fsLogin/login
    volumes:
      - ./config/my.conf:/etc/nginx/conf.d/my.conf
    ports:
      - '8080:8080'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - yangfan_network
    hostname: prometheus
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pushgateway:
    container_name: pushgateway
    hostname: pushgateway
    networks:
      - yangfan_network
    image: prom/pushgateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '9091:9091'

  grafana:
    container_name: grafana
    image: "grafana/grafana:9.5.1"
    user: root
    ports:
      - '3000:3000'
    restart: always
    networks:
      - yangfan_network
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/log:/var/log/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PATHS_CONFIG=/etc/grafana/provisioning/grafana.ini
      - TZ=Asia/Shanghai

  yangfan-master:
    image: registry.cn-hangzhou.aliyuncs.com/yangfanz/master:latest
    container_name: yangfan-master
    networks:
      - yangfan_network
    depends_on:
      - yangfan-server
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml
    ports:
      - '7966:7966'
      - '9093:9093'
      - '9092:9092'

  work:
    image: registry.cn-hangzhou.aliyuncs.com/yangfanz/work:latest
    container_name: work
    networks:
      - yangfan_network
    depends_on:
      - yangfan-server
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml

  yangfan-run:
    image: registry.cn-hangzhou.aliyuncs.com/yangfanz/run:latest
    container_name: yangfan-run
    networks:
      - yangfan_network
    depends_on:
      - yangfan-server
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml

  timer:
    image: registry.cn-hangzhou.aliyuncs.com/yangfanz/timer:latest
    container_name: timer
    networks:
      - yangfan_network
    depends_on:
      - yangfan-server
    restart: always
    volumes:
      - ./config/docker.config.yaml:/yangfan/docker.config.yaml


