name: CI

on:
  push:
    branches:
      - main

jobs:
  server:
    name: Building a server image
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com/yangfanz/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_SERVER }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t server -f server/Dockerfile .
          docker tag server ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_SERVER }}:last
          docker push ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_SERVER }}:last
  timer:
    name: Building a timer image
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com/yangfanz/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_TIMER }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t timer -f timer/Dockerfile .
          docker tag timer ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_TIMER }}:last
          docker push ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_TIMER }}:last
  master:
    name: Building a master image
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com/yangfanz/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_MASTER }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t master -f master/Dockerfile .
          docker tag master ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_MASTER }}:last
          docker push ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_MASTER }}:last
  work:
    name: Building a work image
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com/yangfanz/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_WORK }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t work -f work/Dockerfile .
          docker tag work ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_WORK }}:last
          docker push ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_WORK }}:last
  web:
    name: Building a web image
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com/yangfanz/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_WEB }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t web -f ./web/Dockerfile .
          docker tag web ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_WEB }}:last
          docker push ${{ env.ALIYUN_REGISTRY }}${{ env.IMAGE_NAME_WEB }}:last
