name: CI

on:
  push:
    branches:
      - main

jobs:
  server:
    name: Building a server image
    runs-on: ubuntu-latest
    env:
      REGISTRY: yangfans/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t server -f server/Dockerfile .
          docker tag server ${{ env.REGISTRY }}${{ env.IMAGE_NAME_SERVER }}:v1.${{ github.run_number }}
          docker push ${{ env.REGISTRY }}${{ env.IMAGE_NAME_SERVER }}:v1.${{ github.run_number }}
  timer:
    name: Building a timer image
    runs-on: ubuntu-latest
    env:
      REGISTRY: yangfans/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t timer -f timer/Dockerfile .
          docker tag timer ${{ env.REGISTRY }}${{ env.IMAGE_NAME_TIMER }}:v1.${{ github.run_number }}
          docker push ${{ env.REGISTRY }}${{ env.IMAGE_NAME_TIMER }}:v1.${{ github.run_number }}
  master:
    name: Building a master image
    runs-on: ubuntu-latest
    env:
      REGISTRY: yangfans/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t master -f master/Dockerfile .
          docker tag master ${{ env.REGISTRY }}${{ env.IMAGE_NAME_MASTER }}:v1.${{ github.run_number }}
          docker push ${{ env.REGISTRY }}${{ env.IMAGE_NAME_MASTER }}:v1.${{ github.run_number }}
  work:
    name: Building a work image
    runs-on: ubuntu-latest
    env:
      REGISTRY: yangfans/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t work -f work/Dockerfile .
          docker tag work ${{ env.REGISTRY }}${{ env.IMAGE_NAME_WORK }}:v1.${{ github.run_number }}
          docker push ${{ env.REGISTRY }}${{ env.IMAGE_NAME_WORK }}:v1.${{ github.run_number }}
  web:
    name: Building a web image
    runs-on: ubuntu-latest
    env:
      REGISTRY: yangfans/
      IMAGE_NAME_SERVER: server
      IMAGE_NAME_TIMER: timer
      IMAGE_NAME_MASTER: master
      IMAGE_NAME_WORK: work
      IMAGE_NAME_WEB: web

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t web -f ./web/Dockerfile .
          docker tag web ${{ env.REGISTRY }}${{ env.IMAGE_NAME_WEB }}:v1.${{ github.run_number }}
          docker push ${{ env.REGISTRY }}${{ env.IMAGE_NAME_WEB }}:v1.${{ github.run_number }}
