name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com/test-instructor/yangfan
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t server -f server/Dockerfile .
          docker tag server registry.cn-hangzhou.aliyuncs.com/test-instructor/yangfan:latest
          docker push registry.cn-hangzhou.aliyuncs.com/test-instructor/yangfan:latest

