name: Build and deploy Docker image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-docker-image
  DOCKER_REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build the Go app
        run: go build

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: server/Dockerfile   # 指定 Dockerfile 的路径
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_NAME=myapp

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}