name: Build and deploy server Docker image

on:
  push:
    branches:
      - main
      - dev

env:
  IMAGE_NAME: yangfan-server
  DOCKER_REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print workspace directory
        run: echo "Workspace directory: $GITHUB_WORKSPACE"
      - name: Print github sha
        run: echo "github sha: ${{ github.sha }}"
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

